[package]
name = "hashcaster"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
itertools = "0.13.0"
num-traits = "0.2.19"
rand = "0.8.5"
rayon = "1.10.0"
unroll = "0.1.5"

[features]
parallel = []
default = ["parallel"]
